# development mode
version: '3.5'
services:
  web:
    image: nginx:stable
    ports:
      - "${WEB_PORT:-80}:80"
    networks:
      - log-network
    links:
      - http-log-monitoring
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - log-volume:/logs

  http-log-monitoring:
    image: http-log-monitoring:latest
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${http_proxy}
        no_proxy: ${no_proxy}
    restart: always
    volumes:
      - log-volume:/logs

networks:
  log-network:
    name: log-network
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
volumes:
    log-volume: 
